[[bodies]]
type = "Star"

[[bodies.celestial.template]]
position = [0.0, 0.0, 0.0]
velocity = [0.0, 0.0, 0.0]
mass = 500000.0
size = 300

[[bodies.celestial.mesh]]
base_mesh = { subdivisions = 1, vertices_per_edge = [[12, 17]], num_abberations = 0, num_deformation_cycles = 0 }
tectonic = { num_continents = [1, 2], stress_scale = [0.800, 1.000], shear_scale = [0.200, 1.000], max_propagation_distance = [0.010, 0.100], propagation_falloff = [0.100, 0.200], inactive_stress_threshold = [0.010, 0.100], general_height_scale = [0.800, 1.200], general_shear_scale = [0.800, 1.200], general_compression_scale = [1.000, 1.750], general_transform_scale = [1.100, 1.400] }

[[bodies]]
type = "RockyPlanet"

[[bodies.celestial.template]]
position = [2000.0, 0.0, 0.0]
velocity = [0.0, -0.4, 0.0]
mass = 100.0
size = 50

[[bodies.celestial.mesh]]
base_mesh = { subdivisions = 2, vertices_per_edge = [[4, 6], [2, 3]], num_abberations = 3, num_deformation_cycles = 3 }
tectonic = { num_continents = [13, 25], stress_scale = [1.100, 1.100], shear_scale = [1.100, 1.100], max_propagation_distance = [0.010, 0.010], propagation_falloff = [0.200, 0.200], inactive_stress_threshold = [0.010, 0.010], general_height_scale = [0.600, 0.600], general_shear_scale = [1.100, 1.100], general_compression_scale = [1.200, 1.200], general_transform_scale = [1.000, 1.200] }

[[bodies.celestial.satellites]]
type = "Moon"
[[bodies.celestial.satellites.template]]
position = [450.0, 0.0, 0.0]
velocity = [0.0, 2.0, 0.0]
mass = 4.0
size = 1
[[bodies.celestial.satellites.mesh]]
base_mesh = { subdivisions = 1, vertices_per_edge = [[2, 3]], num_abberations = 0, num_deformation_cycles = 0 }
scaling = { scaling_range_x = [1.000, 1.200], scaling_range_y = [1.000, 1.200], scaling_range_z = [1.000, 1.200] }
noise_settings = { amplitude_range = [0.500, 1.200], scaling_range = [0.200, 1.700], octave_range = [2, 4] }

[[bodies]]
type = "RockyPlanet"

[[bodies.celestial.template]]
position = [2500.0, 129.9, 1200.0]
velocity = [0.0, -0.0, 0.0]
mass = 100.0
size = 50

[[bodies.celestial.mesh]]
base_mesh = { subdivisions = 2, vertices_per_edge = [[4, 6], [2, 3]], num_abberations = 3, num_deformation_cycles = 3 }
tectonic = { num_continents = [13, 25], stress_scale = [1.100, 1.100], shear_scale = [1.100, 1.100], max_propagation_distance = [0.010, 0.010], propagation_falloff = [0.200, 0.200], inactive_stress_threshold = [0.010, 0.010], general_height_scale = [0.600, 0.600], general_shear_scale = [1.100, 1.100], general_compression_scale = [1.200, 1.200], general_transform_scale = [1.000, 1.200] }

[[bodies]]
type = "RockyPlanet"

[[bodies.celestial.template]]
position = [6000.0, -129.9, 0.0]
velocity = [-0.3, 0.2, 0.0]
mass = 100.0
size = 50

[[bodies.celestial.mesh]]
base_mesh = { subdivisions = 2, vertices_per_edge = [[4, 6], [2, 3]], num_abberations = 3, num_deformation_cycles = 3 }
tectonic = { num_continents = [13, 25], stress_scale = [1.100, 1.100], shear_scale = [1.100, 1.100], max_propagation_distance = [0.010, 0.010], propagation_falloff = [0.200, 0.200], inactive_stress_threshold = [0.010, 0.010], general_height_scale = [0.600, 0.600], general_shear_scale = [1.100, 1.100], general_compression_scale = [1.200, 1.200], general_transform_scale = [1.000, 1.200] }
