[categories]
potential = ["mythology", "scientists", "explorers", "adjectives"]

[mythology]
names = [
  "Hephaestus",
  "Vulcan",
  "Svarog",
  "Ogun",
  "Ilmarinen",
  "Goibniu",
  "Brigid",
  "Vishvakarma",
  "Agni",
  "Kubera",
  "Shani",
  "Nergal",
  "Enki",
  "Ninurta",
  "Ereshkigal",
  "Hades",
  "Persephone",
  "Hecate",
  "Atlas",
  "Kronos",
  "Dvalin",
  "Brokkr",
  "Sindri",
  "Loki",
  "Ptah",
  "Anubis",
  "Sekhmet",
  "Tezcatlipoca",
  "Quetzalcoatl",
  "Xolotl",
  "Itzamna",
  "Ah Puch",
  "Supay",
  "Viracocha",
  "Pachamama",
  "Sedna",
  "Nanook",
  "Pangu",
  "Nuwa",
  "Gonggong",
  "Kua Fu",
  "Hou Yi",
  "Ishikoridome",
  "Kagutsuchi",
  "Kanayago",
  "Susanoo",
  "Teliavelis",
  "Veles",
  "Ruaumoko",
  "Tlaltecuhtli",
]

[scientists]
names = [
  "Galileo Galilei",
  "Caroline Herschel",
  "William Herschel",
  "Henrietta Leavitt",
  "Annie Jump Cannon",
  "Cecilia Payne",
  "Edwin Hubble",
  "Vera Rubin",
  "Subrahmanyan Chandrasekhar",
  "Meghnad Saha",
  "Hipparchus",
  "Tycho Brahe",
  "Johannes Kepler",
  "Christiaan Huygens",
  "Urbain Le Verrier",
  "Johann Galle",
  "Giuseppe Piazzi",
  "Heinrich Olbers",
  "Karl Ludwig Hencke",
  "John Russell Hind",
  "Hermann Goldschmidt",
  "Christian Peters",
  "Johann Palisa",
  "Max Wolf",
  "Karl Reinmuth",
  "Grigory Neujmin",
  "Sergey Belyavsky",
  "Eugene Delporte",
  "Hendrik van Gent",
  "Tom Gehrels",
  "Carolyn Shoemaker",
  "Eugene Shoemaker",
  "Clyde Tombaugh",
  "Gerard Kuiper",
  "Jan Oort",
  "Mary Adela Blagg",
  "Nicole Reine Lepaute",
  "Maria Mitchell",
  "Hypatia",
  "Wang Zhenyi",
  "Shen Kuo",
  "Abd al Rahman al Sufi",
  "Ulugh Beg",
  "Aryabhata",
  "Victor Goldschmidt",
  "Friedrich Mohs",
  "James Dwight Dana",
  "Rene Just Hauy",
  "Abraham Gottlob Werner",
  "Georgius Agricola",
]

[explorers]
names = [
  "Auguste Charlois",
  "Paul Henry",
  "Prosper Henry",
  "Eric Walter Elst",
  "Lubos Kohoutek",
  "Antonin Mrkos",
  "Yrjo Vaisala",
  "Heikki Alikoski",
  "Daniel du Toit",
  "James Craig Watson",
  "Edward Bowell",
  "Brian Skiff",
  "Marc Buie",
  "Krisztian Sarneczky",
  "Korado Korlevic",
  "Jean Claude Merlin",
  "Ingrid van Houten Groeneveld",
  "Cornelis van Houten",
  "Tom Van Flandern",
  "James V Scotti",
  "Eleanor Helin",
  "Petr Pravec",
  "Andrea Boattini",
  "Richard Kowalski",
  "Roy Tucker",
  "Jeffrey Larson",
  "Alain Maury",
  "Hiroshi Kaneda",
  "Seiji Ueda",
  "Masaru Arai",
  "Naoto Sato",
  "Henry Comstock",
  "George Hearst",
  "John William Mackay",
  "James Graham Fair",
  "William S OBrien",
  "Ed Schieffelin",
  "Nellie Cashman",
  "George Carmack",
  "Skookum Jim Mason",
  "Tagish Charlie",
  "Kate Carmack",
  "Felice Pedroni",
  "Edward Hargraves",
  "Paddy Hannan",
  "Harold Lasseter",
  "James W Marshall",
  "Robert Henderson",
  "Albert Ernest Kitson",
]

[adjectives]
names = [
  "iron veined",
  "nickel rich",
  "cobalt flecked",
  "stone hearted",
  "metal cored",
  "carbon dark",
  "silicate bright",
  "pitted drifter",
  "tumbling relic",
  "slag crowned",
  "regolith draped",
  "rubble piled",
  "sun scarred",
  "impact bruised",
  "crater lined",
  "dust mantled",
  "shard born",
  "vacuum tempered",
  "ancient fragment",
  "spin tossed",
  "orbit haunted",
  "iron kissed",
  "fractured wanderer",
  "chondrite laced",
  "basalt streaked",
  "ferric stained",
  "magnet stiff",
  "metal scarred",
  "albedo low",
  "siderite cold",
  "stony bound",
  "vein riddled",
  "core bared",
  "slag rimmed",
  "shadow tumbled",
  "oxide dusted",
  "space weathered",
  "blast pocked",
  "brittle spun",
  "dark tumbling",
  "relic speckled",
  "nickel spattered",
  "iron streaked",
  "low gravity",
  "relic hewn",
  "cold forged",
  "ore laden",
  "furnace kissed",
  "arc scarred",
  "meteoritic tough",
]

[satellite.template]
position = [450, 0, 0]
velocity = [0, 2, 0]
size_range = [1, 4]
mass_range = [4, 10]

[satellite.mesh.base_mesh]
subdivisions = 1
vertices_per_edge = [2, 3]
num_abberations = 0
num_deformation_cycles = 0

[satellite.mesh.scaling]
scaling_range_x = [0.8, 1.8]
scaling_range_y = [0.8, 1.5]
scaling_range_z = [0.8, 1.8]

[satellite.mesh.noise_settings]
amplitude_range = [0.5, 1.2]
scaling_range = [0.2, 1.7]
octave_range = [2, 4]
