[satellite_group.template]
number_asteroids = [6, 15]
grouping = "Balanced"
apogee = 8000
perigee = 250
ring_velocity = [0, 2, 0]
size_range = [1, 5]
mass_range = [1, 10]
possible_subtypes = ["DwarfPlanet", "Asteroid"]
