[categories]
potential = ["mythology", "scientists", "explorers", "adjectives"]

[mythology]
names = [
  "Hades",
  "Persephone",
  "Loki",
  "Hel",
  "Anubis",
  "Osiris",
  "Set",
  "Kali",
  "Shiva",
  "Thanatos",
  "Nyx",
  "Erebus",
  "Chaos",
  "Tartarus",
  "Azathoth",
  "Yog-Sothoth",
  "Nyarlathotep",
  "Cthulhu",
  "Shub-Niggurath",
  "Hastur",
  "Dagon",
  "Nodens",
  "Abhoth",
  "Yibb-Tstll",
  "Tsathoggua",
  "Atlach-Nacha",
  "Bokrug",
  "Byatis",
  "Chaugnar Faugn",
  "Cyaegha",
  "Daoloth",
  "Eihort",
  "Gla'aki",
  "Ghroth",
  "Ghatanothoa",
  "Ithaqua",
  "Mnomquah",
  "Nyogtha",
  "Quachil Uttaus",
  "Rhan-Tegoth",
  "Shudde M'ell",
  "Tru'nembra",
  "Ubbo-Sathla",
  "Ythogtha",
  "Zoth-Ommog",
  "Zstylzhemghi",
  "Zvilpogghua",
  "Vorvadoss",
  "Xalafu",
  "Wamp",
]

[scientists]
names = [
  "Albert Einstein",
  "Karl Schwarzschild",
  "Stephen Hawking",
  "Roger Penrose",
  "Kip Thorne",
  "Subrahmanyan Chandrasekhar",
  "John Wheeler",
  "Roy Kerr",
  "Edwin Hubble",
  "Arthur Eddington",
  "David Finkelstein",
  "Werner Israel",
  "Brandon Carter",
  "Martin Rees",
  "Jocelyn Bell Burnell",
  "Antony Hewish",
  "Joseph Taylor",
  "Russell Hulse",
  "Rainer Weiss",
  "Barry Barish",
  "Reinhard Genzel",
  "Andrea Ghez",
  "Saul Perlmutter",
  "Brian Schmidt",
  "Adam Riess",
  "George Smoot",
  "John Mather",
  "Vera Rubin",
  "Fritz Zwicky",
  "Hans Bethe",
  "Fred Hoyle",
  "William Fowler",
  "Cecilia Payne-Gaposchkin",
  "Annie Jump Cannon",
  "Henrietta Leavitt",
  "Harlow Shapley",
  "Georges Lema√Ætre",
  "Alexander Friedmann",
  "Willem de Sitter",
  "Paul Dirac",
  "Lev Landau",
  "Yakov Zel'dovich",
  "Igor Novikov",
  "Jacob Bekenstein",
  "Leonard Susskind",
  "Gerard 't Hooft",
  "Juan Maldacena",
  "Edward Witten",
  "Brian Greene",
]

[explorers]
names = [
  "Neil Armstrong",
  "Buzz Aldrin",
  "Michael Collins",
  "Yuri Gagarin",
  "Valentina Tereshkova",
  "John Glenn",
  "Alan Shepard",
  "Gus Grissom",
  "Roger Chaffee",
  "Ed White",
  "Sally Ride",
  "Mae Jemison",
  "Chris Hadfield",
  "Tim Peake",
  "Samantha Cristoforetti",
  "Captain James T. Kirk",
  "Mr. Spock",
  "Dr. Leonard McCoy",
  "Lt. Uhura",
  "Lt. Sulu",
  "Ensign Chekov",
  "Scotty",
  "Captain Picard",
  "Commander Riker",
  "Counselor Troi",
  "Lt. Commander Data",
  "Lt. Worf",
  "Lt. Commander Geordi La Forge",
  "Captain Janeway",
  "Commander Chakotay",
  "Lt. Tuvok",
  "Ensign Kim",
  "Lt. Torres",
  "Lt. Paris",
  "The Doctor (EMH)",
  "Seven of Nine",
  "Luke Skywalker",
  "Han Solo",
  "Princess Leia",
  "Chewbacca",
  "Obi-Wan Kenobi",
  "Yoda",
  "Darth Vader",
  "Emperor Palpatine",
  "Ellen Ripley",
  "Dave Bowman",
  "HAL 9000",
  "Dr. Heywood Floyd",
  "Joseph Cooper",
  "Dr. Amelia Brand",
]

[adjectives]
names = [
  "Dark",
  "Abyssal",
  "Voracious",
  "Enigmatic",
  "Mysterious",
  "Powerful",
  "Gravitational",
  "Massive",
  "Dense",
  "Invisible",
  "Devouring",
  "Eternal",
  "Cosmic",
  "Singular",
  "Spaghettifying",
  "Relativistic",
  "Extreme",
  "Collapsing",
  "Stellar",
  "Supermassive",
  "Primordial",
  "Radiating",
  "Insatiable",
  "Unfathomable",
  "Timeless",
  "Boundaryless",
  "Infinite",
  "Curved",
  "Warped",
  "Distorting",
  "Swallowing",
  "Crushing",
  "Imploding",
  "Accreting",
  "Jet-producing",
  "Quasar-like",
  "Monstrous",
  "Beastly",
  "Hungry",
  "Silent",
  "Deadly",
  "Lethal",
  "Ominous",
  "Terrifying",
  "Fascinating",
  "Bewildering",
  "Puzzling",
  "Incomprehensible",
  "Mind-bending",
  "Unseen",
]

[celestial.template]
position = [0, 0, 0]
velocity = [0, 0, 0]
mass = 1000000
size = 10

[celestial.mesh.base_mesh]
subdivisions = 1
vertices_per_edge = [[5, 12]]
num_abberations = 1
num_deformation_cycles = 1

[celestial.mesh.tectonic]
num_continents = [1, 1]
stress_scale = [1.0, 5.0]
shear_scale = [0.5, 2.0]
max_propagation_distance = [0.02, 0.2]
propagation_falloff = [0.5, 1.0]
inactive_stress_threshold = [0.02, 0.2]
general_height_scale = [0.5, 1.5]
general_shear_scale = [0.5, 1.5]
general_compression_scale = [1.5, 2.5]
general_transform_scale = [1.2, 1.8]
