[categories]
potential = ["mythology", "scientists", "explorers", "adjectives"]

[mythology]
names = [
  "Nyx",
  "Selene",
  "Eos",
  "Astraea",
  "Iris",
  "Chione",
  "Urania",
  "Boreas",
  "Skadi",
  "Mani",
  "Nott",
  "Idunn",
  "Freya",
  "Nut",
  "Ra",
  "Thoth",
  "Maat",
  "Khonsu",
  "Ishtar",
  "Inanna",
  "Sin",
  "Tiamat",
  "Marduk",
  "Ereshkigal",
  "Chandra",
  "Surya",
  "Vayu",
  "Soma",
  "Ushas",
  "Chang'e",
  "Hou Yi",
  "Nuwa",
  "Pangu",
  "Amaterasu",
  "Tsukuyomi",
  "Hina",
  "Maui",
  "Tangaroa",
  "Rangi",
  "Tawhiri",
  "Sedna",
  "Nanook",
  "Nokomis",
  "Oya",
  "Shango",
  "Yemoja",
  "Quetzalcoatl",
  "Kukulkan",
  "Ix Chel",
  "Inti",
]

[scientists]
names = [
  "Edmond Halley",
  "Caroline Herschel",
  "William Herschel",
  "Charles Messier",
  "Pierre Mechain",
  "Giovanni Cassini",
  "Christiaan Huygens",
  "Tycho Brahe",
  "Johannes Kepler",
  "Galileo Galilei",
  "Hipparchus",
  "Claudius Ptolemy",
  "Nicolaus Copernicus",
  "Isaac Newton",
  "Johann Encke",
  "Giuseppe Piazzi",
  "Maria Mitchell",
  "Henrietta Leavitt",
  "Annie Jump Cannon",
  "Edwin Hubble",
  "Harlow Shapley",
  "Fritz Zwicky",
  "Jan Oort",
  "Gerard Kuiper",
  "Eugene Shoemaker",
  "Carolyn Shoemaker",
  "David Levy",
  "Alan Hale",
  "Thomas Bopp",
  "Yuji Hyakutake",
  "Lubos Kohoutek",
  "Kaoru Ikeya",
  "Tsutomu Seki",
  "Gennady Borisov",
  "Robert Weryk",
  "Alexander Churyumov",
  "Svetlana Gerasimenko",
  "Fred Whipple",
  "Brian Marsden",
  "Donald Yeomans",
  "Liisi Oterma",
  "Minoru Honda",
  "Antonin Mrkos",
  "Ludmila Pajdusakova",
  "Jean Louis Pons",
  "Horace Tuttle",
  "Lewis Swift",
  "Michel Giacobini",
  "Johann Galle",
  "Vera Rubin",
]

[explorers]
names = [
  "Marco Polo",
  "Ibn Battuta",
  "Zheng He",
  "Leif Erikson",
  "Erik the Red",
  "Christopher Columbus",
  "Ferdinand Magellan",
  "Vasco da Gama",
  "James Cook",
  "Abel Tasman",
  "Francis Drake",
  "Roald Amundsen",
  "Ernest Shackleton",
  "Robert Falcon Scott",
  "Matthew Henson",
  "Sacagawea",
  "Meriwether Lewis",
  "William Clark",
  "Tenzing Norgay",
  "Edmund Hillary",
  "Thor Heyerdahl",
  "Pytheas",
  "Hanno the Navigator",
  "Xuanzang",
  "Faxian",
  "Ibn Majid",
  "Al Idrisi",
  "Alexander von Humboldt",
  "James Clark Ross",
  "John Franklin",
  "Gertrude Bell",
  "Isabella Bird",
  "Mary Kingsley",
  "Aurel Stein",
  "Tupaia",
  "Mau Piailug",
  "Nainoa Thompson",
  "Kupe",
  "Hokulea",
  "Giotto",
  "Rosetta",
  "Philae",
  "Stardust",
  "Deep Impact",
  "International Cometary Explorer",
  "Vega 1",
  "Vega 2",
  "Sakigake",
  "Suisei",
  "Voyager 2",
]

[adjectives]
names = [
  "Icebound",
  "Frostlit",
  "Sun-seeking",
  "Long-tailed",
  "Luminous",
  "Transient",
  "Perihelion-bound",
  "Night-glimmering",
  "Sky-shearing",
  "Star-trailing",
  "Dawn-skimming",
  "Halo-crowned",
  "Cold-bright",
  "Light-scattering",
  "Tail-fanning",
  "Dust-laden",
  "Vapor-plumed",
  "Aurora-kissed",
  "Wind-swept",
  "Gossamer-tailed",
  "Silvery",
  "Quickening",
  "Outgassing",
  "Radiant",
  "Fading",
  "Heliocentric",
  "Snow-grained",
  "Sunward",
  "Polar-glinting",
  "Noctilucent",
  "Ice-feathered",
  "Celestine",
  "Ether-bright",
  "Blue-tinged",
  "White-flaring",
  "Ghostlit",
  "Starward",
  "Helio-shocked",
  "Crystal-veined",
  "Pale-flamed",
  "Sky-burnished",
  "Quick-sparking",
  "Far-ranging",
  "Night-slicing",
  "Horizon-brushing",
  "Spark-shedding",
  "Frost-cored",
  "Light-born",
  "Dusty",
  "Evaporative",
]

[satellite.template]
position = [450, 0, 0]
velocity = [0, 2, 0]
size_range = [1, 4]
mass_range = [4, 10]

[satellite.mesh.base_mesh]
subdivisions = 1
vertices_per_edge = [2, 3]
num_abberations = 0
num_deformation_cycles = 0

[satellite.mesh.scaling]
scaling_range_x = [0.8, 1.8]
scaling_range_y = [0.8, 1.5]
scaling_range_z = [0.8, 1.8]

[satellite.mesh.noise_settings]
amplitude_range = [0.5, 1.2]
scaling_range = [0.2, 1.7]
octave_range = [2, 4]
