[categories]
potential = ["mythology", "scientists", "explorers", "adjectives"]

[mythology]
names = [
  "Skadi",
  "Nott",
  "Ymir",
  "Boreas",
  "Khione",
  "Nyx",
  "Erebus",
  "Pluto",
  "Nox",
  "Sedna",
  "Pinga",
  "Tekkeitsertok",
  "Qalupalik",
  "Nanook",
  "Louhi",
  "Tuoni",
  "Loviatar",
  "Ilmarinen",
  "Cailleach",
  "Arawn",
  "Manannan",
  "Morana",
  "Chernobog",
  "Veles",
  "Mictlantecuhtli",
  "Tlaloc",
  "Metztli",
  "Ixchel",
  "Ah Puch",
  "Camazotz",
  "Supay",
  "Mama Killa",
  "Tiamat",
  "Ereshkigal",
  "Nergal",
  "Nanna",
  "Ishtar",
  "Apep",
  "Nut",
  "Geb",
  "Anubis",
  "Anahita",
  "Ahriman",
  "Mithra",
  "Erlik",
  "Umay",
  "Tsukuyomi",
  "Yuki-onna",
  "Chang'e",
  "Dalnim",
]

[scientists]
names = [
  "Clyde Tombaugh",
  "Gerard Kuiper",
  "Eugene Shoemaker",
  "Carolyn Shoemaker",
  "James Christy",
  "Jane Luu",
  "David Jewitt",
  "Mike Brown",
  "Vera Rubin",
  "Maria Zuber",
  "Sarah Stewart",
  "Heidi Hammel",
  "Carl Sagan",
  "Andrew Ingersoll",
  "Jonathan Lunine",
  "Torrence Johnson",
  "Robert Pappalardo",
  "Fran Bagenal",
  "Linda Morabito",
  "Reta Beebe",
  "Nancy Chabot",
  "Louise Prockter",
  "Sara Seager",
  "Michel Mayor",
  "Didier Queloz",
  "Marc Buie",
  "Leslie Young",
  "Will Grundy",
  "Konstantin Batygin",
  "Scott Sheppard",
  "Chad Trujillo",
  "David Rabinowitz",
  "Brett Gladman",
  "Jean-Luc Margot",
  "Phil Christensen",
  "Alfred McEwen",
  "Jeff Moore",
  "Britney Schmidt",
  "Paul Schenk",
  "Vishnu Reddy",
  "Renu Malhotra",
  "Alessandro Morbidelli",
  "William Bottke",
  "Patrick Michel",
  "Meenakshi Wadhwa",
  "Sara Russell",
  "Monica Grady",
  "Athena Coustenis",
  "Larry Soderblom",
  "Giuseppe Colombo",
]

[explorers]
names = [
  "Alan Stern",
  "Edward Stone",
  "Linda Spilker",
  "Carolyn Porco",
  "Marc Rayman",
  "Chris Russell",
  "Andrew Cheng",
  "Scott Bolton",
  "Dante Lauretta",
  "Hal Levison",
  "Lindy Elkins-Tanton",
  "John Casani",
  "Robert Farquhar",
  "Gentry Lee",
  "Michael Malin",
  "Steve Squyres",
  "Peter Smith",
  "Matt Taylor",
  "Andrea Accomazzo",
  "Holger Sierks",
  "Jean-Pierre Bibring",
  "Stephan Ulamec",
  "Junichiro Kawaguchi",
  "Yuichi Tsuda",
  "Makoto Yoshikawa",
  "Hitoshi Kuninaka",
  "Hakan Svedhem",
  "Dmitri Titov",
  "Jean-Pierre Lebreton",
  "Charles Bennett",
  "John Mather",
  "Mike A'Hearn",
  "Colin Pillinger",
  "Lou Friedman",
  "Igor Mitrofanov",
  "Ouyang Ziyuan",
  "Ye Peijian",
  "Zhang Rongqiao",
  "Sun Zezhou",
  "Sarah Al Amiri",
  "Omran Sharaf",
  "Bruce Banerdt",
  "Sean Solomon",
  "Charles Elachi",
  "David Paige",
  "Anthony Colaprete",
  "Jim Bell",
  "Bruce Jakosky",
  "Ken Chambers",
  "Amy Mainzer",
]

[adjectives]
names = [
  "icebound",
  "sunless",
  "airless",
  "lightless",
  "distant",
  "remote",
  "silent",
  "hushed",
  "austere",
  "ashen",
  "frostbitten",
  "frostbound",
  "permafrost-bound",
  "stone-cold",
  "emberless",
  "duskswept",
  "shadowed",
  "star-faint",
  "far-flung",
  "dim-lit",
  "glacial",
  "tundral",
  "aurora-pale",
  "crater-scarred",
  "vacuum-still",
  "night-quiet",
  "frost-veiled",
  "snow-drifted",
  "ice-scoured",
  "sun-starved",
  "polar-dark",
  "blue-shadowed",
  "faint-haloed",
  "twilight-veiled",
  "duskward",
  "subsolar-cold",
  "eclipse-haunted",
  "rim-icy",
  "haze-thin",
  "basalt-gray",
  "hollow-still",
  "far-silent",
  "star-cold",
  "stone-still",
  "dust-pale",
  "ice-glazed",
  "horizon-far",
  "deep-frozen",
  "nightbound",
  "cold-forged",
]

[celestial.template]
position = [1200, 0, 0]
velocity = [0, 10, 0]
mass = 10
size = 3

[celestial.mesh.base_mesh]
subdivisions = 1
vertices_per_edge = [[6, 9]]
num_abberations = 3
num_deformation_cycles = 3

[celestial.mesh.tectonic]
num_continents = [25, 40]
stress_scale = [3.0, 8.0]
shear_scale = [1.0, 1.7]
max_propagation_distance = [0.1, 0.4]
propagation_falloff = [0.8, 1.5]
inactive_stress_threshold = [0.01, 0.1]
general_height_scale = [0.8, 1.2]
general_shear_scale = [10.0, 18.0]
general_compression_scale = [20.0, 40.0]
general_transform_scale = [1.1, 1.4]

[satellite.template]
position = [450, 0, 0]
velocity = [0, 2, 0]
size_range = [1, 4]
mass_range = [4, 10]

[satellite.mesh.base_mesh]
subdivisions = 1
vertices_per_edge = [[2, 3]]
num_abberations = 0
num_deformation_cycles = 0

[satellite.mesh.tectonic]
num_continents = [25, 40]
stress_scale = [3.0, 8.0]
shear_scale = [1.0, 1.7]
max_propagation_distance = [0.1, 0.4]
propagation_falloff = [0.8, 1.5]
inactive_stress_threshold = [0.01, 0.1]
general_height_scale = [0.8, 1.2]
general_shear_scale = [10.0, 18.0]
general_compression_scale = [20.0, 40.0]
general_transform_scale = [1.1, 1.4]

[satellite.mesh.noise_settings]
amplitude_range = [0.5, 1.2]
scaling_range = [0.2, 1.7]
octave_range = [2, 4]
