[categories]
potential = ["mythology", "scientists", "explorers", "adjectives"]

[mythology]
names = [
  "Zeus",
  "Jupiter",
  "Thor",
  "Indra",
  "Tlaloc",
  "Chaac",
  "Perun",
  "Raijin",
  "Fujin",
  "Susanoo",
  "Set",
  "Baal",
  "Hadad",
  "Adad",
  "Enlil",
  "Shu",
  "Tezcatlipoca",
  "Tawhirimatea",
  "Anu",
  "Gukumatz",
  "Quetzalcoatl",
  "Kukulkan",
  "Oya",
  "Shango",
  "Nyame",
  "Ukko",
  "Perkunas",
  "Tarhun",
  "Teshub",
  "Marduk",
  "Vayu",
  "Marut",
  "Pazuzu",
  "Lei Gong",
  "Feng Bo",
  "Yu Shi",
  "Huracan",
  "Stribog",
  "Boreas",
  "Notus",
  "Eurus",
  "Zephyrus",
  "Aeolus",
  "Illapa",
  "Catequil",
  "Sila",
  "Qailertetang",
  "Lono",
  "Taranis",
  "Donar",
]

[scientists]
names = [
  "Galileo Galilei",
  "Johannes Kepler",
  "Christiaan Huygens",
  "Giovanni Cassini",
  "Edmond Halley",
  "William Herschel",
  "Caroline Herschel",
  "Edwin Hubble",
  "Henrietta Leavitt",
  "Annie Jump Cannon",
  "Cecilia Payne Gaposhkin",
  "Jocelyn Bell Burnell",
  "Vera Rubin",
  "Jan Oort",
  "Ejnar Hertzsprung",
  "Henry Norris Russell",
  "Gerard Kuiper",
  "Clyde Tombaugh",
  "Frank Drake",
  "Nancy Grace Roman",
  "Subrahmanyan Chandrasekhar",
  "Meghnad Saha",
  "James Van Allen",
  "Eugene Parker",
  "Carl Sagan",
  "George Hadley",
  "William Ferrel",
  "Vilhelm Bjerknes",
  "Carl Rossby",
  "Svante Arrhenius",
  "John Tyndall",
  "Joseph Fourier",
  "Gordon Dobson",
  "Charles Keeling",
  "Syukuro Manabe",
  "Veerabhadran Ramanathan",
  "Paul Crutzen",
  "Mario Molina",
  "Sherwood Rowland",
  "James Hansen",
  "Inez Fung",
  "Joanne Simpson",
  "Edward Lorenz",
  "Klaus Hasselmann",
  "Susan Solomon",
  "Katharine Hayhoe",
  "Arthur Eddington",
  "Hipparchus",
  "Tycho Brahe",
]

[explorers]
names = [
  "Ferdinand Magellan",
  "Vasco da Gama",
  "James Cook",
  "Zheng He",
  "Ibn Battuta",
  "Marco Polo",
  "Leif Erikson",
  "Roald Amundsen",
  "Ernest Shackleton",
  "Robert Falcon Scott",
  "Vasco Nunez de Balboa",
  "Abel Tasman",
  "Francis Drake",
  "Henry Hudson",
  "Vitus Bering",
  "Samuel de Champlain",
  "David Livingstone",
  "Mungo Park",
  "Mary Kingsley",
  "Isabella Bird",
  "Alexandra David Neel",
  "Nain Singh Rawat",
  "Hiram Bingham",
  "John Wesley Powell",
  "Meriwether Lewis",
  "William Clark",
  "Matthew Henson",
  "Robert Peary",
  "Yuri Gagarin",
  "Valentina Tereshkova",
  "Alexei Leonov",
  "Neil Armstrong",
  "Buzz Aldrin",
  "Michael Collins",
  "Gene Kranz",
  "Chris Kraft",
  "Sergei Korolev",
  "Wernher von Braun",
  "Margaret Hamilton",
  "James Webb",
  "George Mueller",
  "Eileen Collins",
  "Sally Ride",
  "Peggy Whitson",
  "Chris Hadfield",
  "Scott Kelly",
  "Sunita Williams",
  "Eugene Cernan",
  "James Lovell",
  "Thomas Stafford",
]

[adjectives]
names = [
  "Storm Wracked",
  "Banded Colossus",
  "Roaring Maelstrom",
  "Amber Belts",
  "Turbulent Titan",
  "Cyclonic Vastness",
  "Endless Vortices",
  "Thunder Laden",
  "Cloud Shrouded",
  "Pressure Forged",
  "Dusky Bands",
  "Stratospheric Giant",
  "Swirling Behemoth",
  "Jet Streamed",
  "Lightning Veined",
  "Hypnotic Gyres",
  "Gale Bound",
  "Polar Hexagoned",
  "Shear Torn",
  "Coriolis Driven",
  "Deep Atmosphered",
  "Ochre Striped",
  "Boiling Skies",
  "Vortex Crowned",
  "Hydrogen Rich",
  "Helium Heavy",
  "Methane Tinted",
  "Ammonia Laced",
  "Radiant Bands",
  "Great Stormed",
  "Cyclone Spotted",
  "Wind Sculpted",
  "Belt Zoned",
  "Cloud Banked",
  "Turbulence Riven",
  "Gravity Dominant",
  "Auroral Rimmed",
  "Haze Layered",
  "Storm Belted",
  "Jet Latticed",
  "Whirlpool Hearted",
  "Thunderstorm Strewn",
  "Squall Ringed",
  "Pressure Layered",
  "Colossally Banded",
  "Atmosphere Oceanic",
  "Convection Fueled",
  "Storm Horizon",
  "Band Wrapped",
  "Monsoon Hearted",
]

[celestial.template]
position = [500, 0, 0]
velocity = [0, 7, 0]
mass = 1000
size = 35

[celestial.mesh.base_mesh]
subdivisions = 1
vertices_per_edge = [[10, 13]]
num_abberations = 0
num_deformation_cycles = 0

[celestial.mesh.tectonic]
num_continents = [3, 8]
stress_scale = [0.8, 1.0]
shear_scale = [0.2, 1.0]
max_propagation_distance = [0.01, 0.01]
propagation_falloff = [0.2, 0.2]
inactive_stress_threshold = [0.01, 0.01]
general_height_scale = [0.8, 1.2]
general_shear_scale = [0.8, 1.2]
general_compression_scale = [1.0, 1.0]
general_transform_scale = [1.0, 1.0]
