[categories]
potential = ["mythology", "scientists", "explorers", "adjectives"]

[mythology]
names = [
  "Boreas",
  "Khione",
  "Skadi",
  "Ullr",
  "Ymir",
  "Njord",
  "Aegir",
  "Ran",
  "Nott",
  "Sedna",
  "Sila",
  "Nanook",
  "Pinga",
  "Cailleach",
  "Manannan",
  "Lir",
  "Dylan",
  "Morana",
  "Stribog",
  "Veles",
  "Perkunas",
  "Varuna",
  "Vayu",
  "Himavana",
  "Ganga",
  "Xuanwu",
  "Feng Po Po",
  "Gonggong",
  "Yuki-onna",
  "Fujin",
  "Susanoo",
  "Tangaroa",
  "Tlaloc",
  "Chalchiuhtlicue",
  "Itztlacoliuhqui",
  "Huracan",
  "Chaac",
  "Anahita",
  "Vayu-Vata",
  "Tishtrya",
  "Enlil",
  "Enki",
  "Tiamat",
  "Oya",
  "Olokun",
  "Yemoja",
  "Tengri",
  "Pakkanen",
  "Louhi",
  "Vainamoinen",
]

[scientists]
names = [
  "Galileo Galilei",
  "Nicolaus Copernicus",
  "Johannes Kepler",
  "Tycho Brahe",
  "William Herschel",
  "Caroline Herschel",
  "Urbain Le Verrier",
  "John Couch Adams",
  "Johann Galle",
  "Alexis Bouvard",
  "Clyde Tombaugh",
  "Gerard Kuiper",
  "Jan Oort",
  "Edwin Hubble",
  "Vera Rubin",
  "Cecilia Payne-Gaposchkin",
  "Annie Jump Cannon",
  "Henrietta Leavitt",
  "Jocelyn Bell Burnell",
  "Maria Mitchell",
  "Asaph Hall",
  "Giuseppe Piazzi",
  "Christiaan Huygens",
  "Giovanni Cassini",
  "Edmond Halley",
  "Percival Lowell",
  "Vesto Slipher",
  "James Van Allen",
  "Eugene Shoemaker",
  "Carolyn Shoemaker",
  "Carolyn Porco",
  "Linda Spilker",
  "Sarah Horst",
  "Heidi Hammel",
  "Reta Beebe",
  "Maria Zuber",
  "Farouk El-Baz",
  "Alan Stern",
  "Fran Bagenal",
  "Imke de Pater",
  "Leigh Fletcher",
  "Jonathan Fortney",
  "Tristan Guillot",
  "Candice Hansen",
  "Robert Pappalardo",
  "Torrence Johnson",
  "Linda Morabito",
  "Jill Tarter",
  "Subrahmanyan Chandrasekhar",
  "Nasir al-Din al-Tusi",
]

[explorers]
names = [
  "Fridtjof Nansen",
  "Roald Amundsen",
  "Robert Falcon Scott",
  "Ernest Shackleton",
  "Matthew Henson",
  "Robert Peary",
  "James Clark Ross",
  "John Franklin",
  "Douglas Mawson",
  "Richard Byrd",
  "Knud Rasmussen",
  "Tom Crean",
  "Hjalmar Johansen",
  "Carsten Borchgrevink",
  "Frank Worsley",
  "Ann Bancroft",
  "Liv Arnesen",
  "Felicity Aston",
  "Ranulph Fiennes",
  "Borge Ousland",
  "Henry Larsen",
  "Otto Sverdrup",
  "Salomon Andree",
  "Umberto Nobile",
  "Vilhjalmur Stefansson",
  "Jean-Baptiste Charcot",
  "Louis Bernacchi",
  "Xavier Mertz",
  "Apsley Cherry-Garrard",
  "Richard Weber",
  "Mike Horn",
  "Pen Hadow",
  "Inge Solheim",
  "Yuri Gagarin",
  "Valentina Tereshkova",
  "Alexei Leonov",
  "Neil Armstrong",
  "Buzz Aldrin",
  "Michael Collins",
  "John Glenn",
  "Alan Shepard",
  "Jim Lovell",
  "Frank Borman",
  "Sally Ride",
  "Mae Jemison",
  "Guion Bluford",
  "Peggy Whitson",
  "Chris Hadfield",
  "Samantha Cristoforetti",
  "Yang Liwei",
]

[adjectives]
names = [
  "Frostbound",
  "Glacial",
  "Gelid",
  "Subzero",
  "Hyperborean",
  "Boreal",
  "Arctic",
  "Antarctic",
  "Cryogenic",
  "Rimebound",
  "Icebound",
  "Ice-locked",
  "Ice-wreathed",
  "Snow-laden",
  "Rimeswept",
  "Storm-banded",
  "Cloud-shrouded",
  "Haze-draped",
  "Aurora-crowned",
  "Blue-shifted",
  "Cerulean",
  "Cobalt",
  "Sapphire",
  "Azure",
  "Cyanic",
  "Teal",
  "Lazuline",
  "Indigo",
  "Methane-blue",
  "Polar-night",
  "Sun-distant",
  "Distant",
  "Remote",
  "Shadow-drenched",
  "Noctilucent",
  "Katabatic",
  "Circumpolar",
  "Tempestuous",
  "Wind-shorn",
  "Gale-swept",
  "Permafrosted",
  "Glacier-born",
  "Frost-veined",
  "Diamond-hard",
  "Crystal-cold",
  "Hibernal",
  "Ice-veiled",
  "Deep-azure",
  "Far-flung",
  "Aphelion-far",
]

[celestial.template]
position = [800, 0, 0]
velocity = [0, 5, 0]
mass = 50
size = 45
