[categories]
potential = ["mythology", "scientists", "explorers", "adjectives"]

[mythology]
names = [
  "Selene",
  "Luna",
  "Diana",
  "Artemis",
  "Hecate",
  "Phoebe",
  "Mani",
  "Chandra",
  "Soma",
  "Tsukuyomi",
  "Chang'e",
  "Houyi",
  "Khonsu",
  "Thoth",
  "Nanna",
  "Sin",
  "Yarikh",
  "Ixchel",
  "Tecciztecatl",
  "Coyolxauhqui",
  "Metztli",
  "Mama Killa",
  "Huitaca",
  "Anningan",
  "Alignnaq",
  "Rona",
  "Hina",
  "Mahina",
  "Jaci",
  "Mawu",
  "Bendis",
  "Men",
  "Kuu",
  "Arianrhod",
  "Cerridwen",
  "Xbalanque",
  "Ratri",
  "Dewi Ratih",
  "Qamar",
  "Hinauri",
  "Mawu-Lisa",
  "Kusuh",
  "Iah",
  "Nokomis",
  "Endymion",
  "Mene",
  "Mah",
  "Dewi Bulan",
  "Mesiats",
  "Yue Lao",
]

[scientists]
names = [
  "Galileo Galilei",
  "Johannes Kepler",
  "Nicolaus Copernicus",
  "Tycho Brahe",
  "Christiaan Huygens",
  "Giovanni Cassini",
  "Edmond Halley",
  "William Herschel",
  "Caroline Herschel",
  "John Herschel",
  "Hipparchus",
  "Claudius Ptolemy",
  "Abd al-Rahman al-Sufi",
  "Ibn al-Haytham",
  "Omar Khayyam",
  "Ulugh Beg",
  "Aryabhata",
  "Bhaskara II",
  "Subrahmanyan Chandrasekhar",
  "Meghnad Saha",
  "Jan Oort",
  "Fritz Zwicky",
  "Harlow Shapley",
  "Arthur Eddington",
  "Ejnar Hertzsprung",
  "Henry Norris Russell",
  "Cecilia Payne-Gaposchkin",
  "Annie Jump Cannon",
  "Henrietta Leavitt",
  "Vera Rubin",
  "Nancy Grace Roman",
  "Jocelyn Bell Burnell",
  "Maria Mitchell",
  "Gerard Kuiper",
  "Harold Urey",
  "Eugene Shoemaker",
  "Carolyn Shoemaker",
  "James Van Allen",
  "Karl Jansky",
  "James Christy",
  "Don Wilhelms",
  "Maria Zuber",
  "Zdenek Kopal",
  "Gilbert Fielder",
  "Patrick Moore",
  "George Howard Darwin",
  "Johann Schroter",
  "Johann Heinrich Madler",
  "Warren de la Rue",
  "Zhang Heng",
]

[explorers]
names = [
  "Neil Armstrong",
  "Buzz Aldrin",
  "Michael Collins",
  "Pete Conrad",
  "Alan Bean",
  "Alan Shepard",
  "Edgar Mitchell",
  "David Scott",
  "James Irwin",
  "John Young",
  "Charles Duke",
  "Eugene Cernan",
  "Harrison Schmitt",
  "Yuri Gagarin",
  "Alexei Leonov",
  "Valentina Tereshkova",
  "John Glenn",
  "Sally Ride",
  "Mae Jemison",
  "Eileen Collins",
  "Peggy Whitson",
  "Chris Hadfield",
  "Tim Peake",
  "Luca Parmitano",
  "Yang Liwei",
  "Guion Bluford",
  "Sunita Williams",
  "Charles Bolden",
  "Scott Kelly",
  "Oleg Artemyev",
  "Ferdinand Magellan",
  "Zheng He",
  "Ibn Battuta",
  "Marco Polo",
  "Vasco da Gama",
  "James Cook",
  "Roald Amundsen",
  "Ernest Shackleton",
  "Leif Erikson",
  "Bartolomeu Dias",
  "Francis Drake",
  "Henry Hudson",
  "Matthew Henson",
  "Jacques Cartier",
  "Abel Tasman",
  "Pytheas",
  "Tupaia",
  "Kupe",
  "Nain Singh Rawat",
  "Ibn Majid",
]

[adjectives]
names = [
  "tidal",
  "silvery",
  "cratered",
  "pearlescent",
  "pale",
  "gleaming",
  "ashen",
  "argent",
  "shadowed",
  "luminous",
  "glacial",
  "frostbitten",
  "pitted",
  "basaltic",
  "airless",
  "tranquil",
  "serene",
  "waxing",
  "waning",
  "crescent",
  "gibbous",
  "full-faced",
  "nightbound",
  "tidally locked",
  "synchronous",
  "starlit",
  "umbral",
  "penumbral",
  "argentine",
  "lunar",
  "attendant",
  "watchful",
  "ghostly",
  "silvered",
  "crater-scarred",
  "tideworn",
  "pallid",
  "cold-lit",
  "duskward",
  "ancient",
  "pockmarked",
  "bone-white",
  "noctilucent",
  "ethereal",
  "selenian",
  "mare-streaked",
  "mare-darkened",
  "regolithic",
  "beaconlike",
  "steadfast",
]

[satellite.template]
position = [450, 0, 0]
velocity = [0, 2, 0]
size_range = [1, 4]
mass_range = [4, 10]

[satellite.mesh.base_mesh]
subdivisions = 1
vertices_per_edge = [[2, 3]]
num_abberations = 0
num_deformation_cycles = 0

[satellite.mesh.noise_settings]
amplitude_range = [0.5, 1.2]
scaling_range = [0.2, 1.7]
octave_range = [2, 4]

[satellite.mesh.tectonic]
num_continents = [13, 25]
stress_scale = [1.1, 1.5]
shear_scale = [1.1, 1.2]
max_propagation_distance = [0.13, 0.15]
propagation_falloff = [0.015, 0.02]
inactive_stress_threshold = [0.01, 0.015]
general_height_scale = [0.5, 0.5]
general_shear_scale = [1.0, 1.2]
general_compression_scale = [1.1, 1.2]
general_transform_scale = [1.0, 1.2]
